const ATTENDANCE_MARK_TYPES = ['checkIn', 'checkOut'];
const OVERVIEW_STATUS_FILTERS = ['checked_in', 'checked_out'];
const DEFAULT_BRANCH_RADIUS_METERS = 120;
const MAX_ALLOWED_ACCURACY_METERS = 80;
const DEFAULT_SHIFT_START = '09:00';
const DEFAULT_SHIFT_END = '18:00';
const DEFAULT_GRACE_MINUTES_LATE = 15;
const UAE_OFFSET_MINUTES = 240;
// TEMP: set to false before production release.
const ALLOW_PAST_DATE_ATTENDANCE = true;

module.exports = {
  ATTENDANCE_MARK_TYPES,
  OVERVIEW_STATUS_FILTERS,
  DEFAULT_BRANCH_RADIUS_METERS,
  MAX_ALLOWED_ACCURACY_METERS,
  DEFAULT_SHIFT_START,
  DEFAULT_SHIFT_END,
  DEFAULT_GRACE_MINUTES_LATE,
  UAE_OFFSET_MINUTES,
  ALLOW_PAST_DATE_ATTENDANCE,
};
